// Arreglo del banco de preguntas
const pruebas = [
    {
        preguntas: [
            {   id: 1,
                enunciado: "¿Estarías de acuerdo en escribir artículos en la sección de negocios de un periódico?",
                areaInteres: "Administrativo",
                aptitudes: false,
            },
            {   id: 2,
                enunciado: "¿Te gustaría organizar una fiesta de cumpleaños para uno de tus amigos?",
                areaInteres: "Administrativo",
                aptitudes: true,
            },
            {   id: 3,
                enunciado: "¿Te gustaría liderar o crear un plan urbanístico en tu barrio? ",
                areaInteres: "Artística",
                aptitudes: false,
            },
            {   id: 4,
                enunciado: "¿Ante una situación difícil piensas positivamente? ",
                areaInteres: "Medicina y Ciencias de la Salud",
                aptitudes: true,
            },
            {   id: 5,
                enunciado: "¿Se ofrecería como voluntario para ayudar a las personas heridas por un accidente o cual otra situación?",
                areaInteres: "Defensa y Seguridad",
                aptitudes: false,
            },
            {   id: 6,
                enunciado: "¿Cuando eras niño, ¿querías saber cómo estaban construidos tus juguetes?",
                areaInteres: "Ingeniería y Computación",
                aptitudes: false,
            },
            {   id: 7,
                enunciado: "¿Te interesan más los misterios de la naturaleza que la tecnología?",
                areaInteres: "Ciencias exactas y Agrarias.",
                aptitudes: true,
            },
            {   id: 8,
                enunciado: "¿Escuchas con atención los problemas que te plantean tus amigos?",
                areaInteres: "Medicina y Ciencias de la Salud",
                aptitudes: false,
            },
            {   id: 9,
                enunciado: "¿Puedes sugerir que expliques a tus compañeros algo que no entiendan?",
                areaInteres: "Humanidades",
                aptitudes: false,
            },
            {   id: 10,
                enunciado: "¿Te consideras exigente y crítico con tu equipo de trabajo cuando hacen los trabajos en clase?",
                areaInteres: "Ingeniería y Computación",
                aptitudes: true,
            },
            // {   id: 11,
            //     enunciado: "¿Te gusta armar rompecabezas?",
            //     areaInteres: "Artística",
            //     aptitudes: false,
            // },
            // {   id: 12,
            //     enunciado: "¿Te gustaría conocer la diferencia entre macroeconomía y microeconomía?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 13,
            //     enunciado: "¿Te sientes distinto o importante cuando usas uniforme?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: true,
            // },
            // {   id: 14,
            //     enunciado: "¿Crees que siendo profesional te animarías a participar haciendo acrobacias aéreas?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 15,
            //     enunciado: "¿Organizas tu dinero o ahorros de manera que te alcance hasta el próximo mes para comprar lo que necesitas?",
            //     areaInteres: "Administrativo",
            //     aptitudes: true,
            // },
            // {   id: 16,
            //     enunciado: "¿Crees que convences de manera fácil a otras personas sobre la de la verdad de tus argumentos?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 17,
            //     enunciado: "¿Le gustaría ser notificado de nuevos descubrimientos realizados en el origen del universo?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 18,
            //     enunciado: "¿Actúas rápidamente ante cualquier situación que te necesiten?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: true,
            // },
            // {   id: 19,
            //     enunciado: "¿Eres perseverante para resolver un problema matemático de difícil solución?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 20,
            //     enunciado: "¿Aceptarías planificar, organizar y dirigir una empresa?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 21,
            //     enunciado: "¿Eres tú el que trae alegría a las fiestas?",
            //     areaInteres: "Artísctico",
            //     aptitudes: false,
            // },
            // {   id: 22,
            //     enunciado: "¿Consideras más importantes los detalles que otra cosa?",
            //     areaInteres: "Artístico",
            //     aptitudes: true,
            // },
            // {   id: 23,
            //     enunciado: "¿Te gustaría trabajar en el ámbito hospitalario?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 24,
            //     enunciado: "¿Te gusta mantener el orden en tu habitación?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 25,
            //     enunciado: "¿Pasas horas leyendo un libro?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 26,
            //     enunciado: "¿Planificas tu día antes de iniciarlo?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: true,
            // },
            // {   id: 27,
            //     enunciado: "¿Ha desarrollado una relación casi personal con tu computadora?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 28,
            //     enunciado: "¿Te gusta dar forma con plastilina?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 29,
            //     enunciado: "¿Con qué frecuencia ayudas a una persona con condiciones físicas en la calle?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: true,
            // },
            // {   id: 30,
            //     enunciado: "¿Crees que es importante fomentar las actitudes críticas y la participación desde el inicio de la educación secundaria?",
            //     areaInteres: "Humanidades",
            //     aptitudes: true,
            // },
            // //------------------------------------------------------------------------
            // {   id: 31,
            //     enunciado: "¿Acepta que las mujeres ingresen al ejército bajo las mismas reglas que los hombres?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 32,
            //     enunciado: "¿Te gustaría ser la persona que crea técnicas para descubrir patologías de enfermedades?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 33,
            //     enunciado: "¿Participarías en una campaña para prevenir una enfermedad?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 34,
            //     enunciado: "¿El pasado y el desarrollo humano son temas que te interesan?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 35,
            //     enunciado: "¿Participarías en un proyecto para estudiar los movimientos sísmicos y sus consecuencias?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 36,
            //     enunciado: "¿Utiliza un día a la semana fuera de la escuela para actividades físicas?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 37,
            //     enunciado: "¿Te interesan las actividades de mucha acción y de reacción rápida en situaciones imprevistas y de algún peligro?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 38,
            //     enunciado: "¿Te gustaría trabajar en la NASA?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 39,
            //     enunciado: "¿Te gusta más el trabajo manual que el intelectual?",
            //     areaInteres: "Artístico",
            //     aptitudes: true,
            // },
            // {   id: 40,
            //     enunciado: "¿Ofrecerías tu servicio como profesional para ayudar a otros, aunque debas renunciar a momentos agradables?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: true,
            // },
            // {   id: 41,
            //     enunciado: "¿investigas sobre la violencia en el fútbol?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 42,
            //     enunciado: "¿Te gustaría trabajar en un laboratorio en el que se hagan análisis o experimentos mientras estudias?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 43,
            //     enunciado: "¿Arriesgarías tu vida con tal de salvar la vida de una persona desconocida?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: true,
            // },
            // {   id: 44,
            //     enunciado: "¿Te gustaría capacitarte en cursos de primeros auxilios?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 45,
            //     enunciado: "¿Aceptarías comenzar tantas veces como fuera necesario hasta alcanzar un objetivo que deseas?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 46,
            //     enunciado: "¿Distribuyes tus horas diarias de manera que puedas hacer lo que has planeado previamente?",
            //     areaInteres: "Administrativo",
            //     aptitudes: true,
            // },
            // {   id: 47,
            //     enunciado: "¿Tomarías un curso que te enseñe a fabricar los instrumentos y/o piezas de las maquinas o elementos con los que laboras?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 48,
            //     enunciado: "¿Elegirías una profesión la cual te exigiera permanecer alejado de tu familia por varios meses, por ejemplo, el marino?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 49,
            //     enunciado: "¿Estarías de acuerdo en radicarte en una zona agrícola-ganadera para ejercer tus labores profesionales?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 50,
            //     enunciado: "¿Cuándo te encuentras trabajando de forma grupal, te animas a producir ideas originales, que puedan ser tenidas en cuenta?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 51,
            //     enunciado: "¿Te resulta sencillo coordinar y liderar grupos de trabajo?",
            //     areaInteres: "Administrativo",
            //     aptitudes: true,
            // },
            // {   id: 52,
            //     enunciado: "¿Te resultó llamativo estudiar las ciencias biológicas?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 53,
            //     enunciado: "¿Si una empresa grande requiere un Profesional como gerente de comercialización, te sentirías cómodo llevando a cabo ese rol?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 54,
            //     enunciado: "¿Participarías en un proyecto nacional de desarrollo de la principal fuente de recursos de tu ciudad?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 55,
            //     enunciado: "¿Te interesa saber las causas que determinan ciertos fenómenos, aunque el conocer dichas causas no altere tu vida?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: true,
            // },
            // {   id: 56,
            //     enunciado: "¿Te enteraste alguna vez de algún filosofo o escritor que tuviera tus mismas ideas con antelación?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 57,
            //     enunciado: "¿Anhelarías recibir de regalo de cumpleaños un instrumento musical?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 58,
            //     enunciado: "¿Estás dispuesto a colaborar con el cumplimiento de las normas en los lugares públicos?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 59,
            //     enunciado: "¿Consideras que tus ideas son importantes, y haces todo lo que este a tu alcance para ponerlas en práctica?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: true,
            // },
            // {   id: 60,
            //     enunciado: "¿Cuándo se daña un aparato o electrodoméstico en tu casa, te propones a repararlo lo antes posible?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 61,
            //     enunciado: "¿Te unirías a un grupo de trabajo orientado a preservar la flora y fauna en extinción?",
            //     areaInteres: "Ciencias Exactas y Agragias",
            //     aptitudes: false,
            // },
            // {   id: 62,
            //     enunciado: "¿Leerías literatura y revistas relacionadas con avances científicos y tecnológicos en el área de la salud?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 63,
            //     enunciado: "¿Consideras necesario e importante conservar las raíces culturales de nuestro país?",
            //     areaInteres: "Humanidades",
            //     aptitudes: true,
            // },
            // {   id: 64,
            //     enunciado: "¿Te animarías a realizar una investigación que ayudara a hacer más equitativa la distribución de la riqueza?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 65,
            //     enunciado: "¿Te interesaría realizar tareas auxiliares en una nave, por ejemplo: arriado e izado de velas, arreglo de averías, conservación de motores, pintura y conservación del casco, entre otras?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 66,
            //     enunciado: "¿Consideras importante que un país deba adquirir la más alta tecnología armamentista, como dé lugar?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: true,
            // },
            // {   id: 67,
            //     enunciado: "¿Consideras importantes para tu vida los valores de justicia y libertad?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 68,
            //     enunciado: "¿Si una industria de productos alimenticios te propone realizar prácticas pagas en el sector de control de calidad, accederías a esta propuesta?",
            //     areaInteres: "Ciencias Exactas y Agragias",
            //     aptitudes: false,
            // },
            // {   id: 69,
            //     enunciado: "¿Crees que la salud publica debería ser gratuita, prioritaria y eficiente para todos?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: true,
            // },
            // {   id: 70,
            //     enunciado: "Te gustaría realizar una investigación sobre alguna nueva vacuna",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 71,
            //     enunciado: "¿Si entraras a trabajar en una empresa, te gustaría cumplir el rol de coordinador?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 72,
            //     enunciado: "¿Cuándo tus amigos tienen conflictos y discuten, sueles tomar el rol de mediador?",
            //     areaInteres: "Humanidades",
            //     aptitudes: true,
            // },
            // {   id: 73,
            //     enunciado: "¿Te parecería la idea de formar un cuerpo de soldados profesionales?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 74,
            //     enunciado: "¿Te atreverías a luchar por una causa que sea justa hasta llegar a las ultimas consecuencias?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 75,
            //     enunciado: "¿Te interesaría realizar una investigación científica sobre cultivos agrícolas?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 76,
            //     enunciado: "¿Crearías un nuevo diseño de una prenda que no esté a la moda, para exponerlo en una reunión?",
            //     areaInteres: "Artístico",
            //     aptitudes: true,
            // },
            // {   id: 77,
            //     enunciado: "¿Te interesaría visitar un observatorio astronómico para conocer de cerca el funcionamiento de los aparatos?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 78,
            //     enunciado: "¿Te gustaría dirigir el área de importación y exportación de una empresa?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 79,
            //     enunciado: "Al entrar a un lugar nuevo con personas que no conoces, ¿te limitas a mantener contacto con las personas?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: true,
            // },
            // {   id: 80,
            //     enunciado: "¿Te gustaría trabajar con niños?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 81,
            //     enunciado: "¿Diseñarías un afiche o cartel para una campaña contra el Sida?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 82,
            //     enunciado: "¿Te atreverías a dirigir un grupo de teatro de forma independiente?",
            //     areaInteres: "Artístico",
            //     aptitudes: true,
            // },
            // {   id: 83,
            //     enunciado: "En una empresa automotriz están solicitando un gerente para su área de producción, ¿enviarías tu hoja de vida para esta vacante?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 84,
            //     enunciado: "¿Te gustaría hacer parte de un grupo de defensa internacional dentro de alguna fuerza armada?",
            //     areaInteres: "Defensa y Seguridad",
            //     aptitudes: false,
            // },
            // {   id: 85,
            //     enunciado: "¿Pagarías tus estudios trabajando para una auditoría?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },{   id: 86,
            //     enunciado: "¿Sientes que debes defender aquellas causas perdidas?",
            //     areaInteres: "Humanidades",
            //     aptitudes: true,
            // },
            // {   id: 87,
            //     enunciado: "En medio de una emergencia epidémica, ¿te gustaría participar en una campaña brindando tu ayuda?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 88,
            //     enunciado: "¿Conoces el significado de ADN y ARN?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 89,
            //     enunciado: "¿Te gustaría elegir una carrera donde se utilice como instrumento un idioma extranjero?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 90,
            //     enunciado: "¿Te parece mucho mas divertido trabajar con máquinas, objetos, que trabajar con personas?",
            //     areaInteres: "Ingeniería y computación",
            //     aptitudes: true,
            // },
            // {   id: 91,
            //     enunciado: "¿Te gustaría trabajar como asesor contable en una empresa reconocida?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },
            // {   id: 92,
            //     enunciado: "Si te ofrecieran solidariamente cuidar de una persona enferma, ¿lo harías?",
            //     areaInteres: "Medicina y Ciencias de la Salud",
            //     aptitudes: false,
            // },
            // {   id: 93,
            //     enunciado: "¿Te llaman la atención las investigaciones sobre los misterios del universo, por ejemplo, los agujeros negros?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: false,
            // },
            // {   id: 94,
            //     enunciado: "¿Te parece que trabajar de manera individual es más efectivo y rápido que en grupos?",
            //     areaInteres: "Ciencias Exactas y Agrarias",
            //     aptitudes: true,
            // },
            // {   id: 95,
            //     enunciado: "¿Dedicarías voluntariamente pasar tiempo ayudando a personas que tienen necesidades o carencias?",
            //     areaInteres: "Humanidades",
            //     aptitudes: false,
            // },
            // {   id: 96,
            //     enunciado: "Cuando quieres decorar un ambiente o elegir tus prendas de vestir, tienes en cuenta ¿que los colores combinen, el estilo de los muebles o las telas?",
            //     areaInteres: "Artístico",
            //     aptitudes: false,
            // },
            // {   id: 97,
            //     enunciado: "Si te dieran la oportunidad de trabajar como profesional dirigiendo la construcción de una empresa hidroeléctrica, ¿aceptarías?",
            //     areaInteres: "Ingeniería y Computación",
            //     aptitudes: false,
            // },
            // {   id: 98,
            //     enunciado: "¿Conoces el termino económico ‘’PIB’’?",
            //     areaInteres: "Administrativo",
            //     aptitudes: false,
            // },


        ]
    }
]





// Arreglo pruebas de test
// const pruebas = [
//     {
//         preguntas: [
//             {
//                 id: 1,
//                 enunciado: "¿Aceptarías trabajar escribiendo artículos en la sección económica de un diario?",
//                 areaInteres: "Administrativo",
//                 aptitudes: true
//             },
//             {
//                 id: 2,
//                 enunciado: "¿Pasarías varias horas leyendo algún libro de tu interés?",
//                 areaInteres: "Humanidades",
//                 aptitudes: false
//             },
//             {
//                 id: 3,
//                 enunciado: "¿Te interesan los temas relacionados al pasado y a la evolución del hombre?",
//                 areaInteres: "Humanidades",
//                 aptitudes: false
//             },
//             {
//                 id: 4,
//                 enunciado: "¿Te gustaría conocer la diferencia entre macroeconomía y microeconomía?",
//                 areaInteres: "Administrativo",
//                 aptitudes: false
//             },
            // Agregar más preguntas para la Prueba 1 aquí...
    //     ]
    // },
    // {
    //     preguntas: [
    //         {
    //             id: 1,
    //             enunciado: "Pregunta 1",
    //             areaInteres: "Área de interés 3",
    //             aptitudes: true
    //         },
    //         {
    //             id: 2,
    //             enunciado: "Pregunta 2",
    //             areaInteres: "Área de interés 4",
    //             aptitudes: false
    //         },
    //         // Agregar más preguntas para la Prueba 2 aquí...
    //     ]
    // },
    // Agregar más pruebas aquí...
// ];